---
title: "p8105_hw6_mp3653"
author: "Matthew Perrotta"
date: "November 27, 2018"
output: github_document
---

### Load Packages
```{r}
library(tidyverse)
```

# Problem 1
### Import and Clean Data
```{r}
homicide_data = read_csv('https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv') %>%
  janitor::clean_names() %>% 
  unite(city_state, c(city, state), sep = ", ", remove = FALSE) %>% 
  filter(!(city_state %in% c('Dallas, TX', 'Phoenix, AZ', 'Kansas City, MO', 'Tulsa, AL'))) %>% 
  mutate(outcome = as.factor(ifelse(disposition == 'Closed by arrest', 'solved', 'unsolved')),
         victim_age = as.numeric(victim_age),
         victim_race = ifelse(victim_race == 'White', 'white', 'non-white'),
         victim_race = fct_relevel(victim_race, 'white'),
         victim_sex = as.factor(victim_sex))
```

### Logistic Regression
Baltimore
```{r}
baltimore = homicide_data %>% 
  filter(city == 'Baltimore')

baltimore_lr = glm(outcome ~ victim_age + victim_sex + victim_race, data = baltimore, family = binomial())

baltimore_lr %>% broom::tidy() %>% 
  janitor::clean_names() %>% 
  mutate(OR = exp(estimate),
         lower_bound = exp(estimate - (1.96 * std_error)),
         upper_bound = exp(estimate + (1.96 * std_error))) %>% 
  filter(term == 'victim_racenon-white') %>% 
  select(OR, lower_bound, upper_bound) %>% 
  knitr::kable()

```

All cities
```{r}
city_lr = homicide_data %>% 
  group_by(city) %>% 
  nest() %>% 
  mutate(models = map(data, ~ glm(outcome ~ victim_age + victim_sex + victim_race, data = .x, family = binomial())),
         models = map(models, broom::tidy)) %>% 
  select(-data) %>% 
  unnest() %>% 
  janitor::clean_names() %>% 
  mutate(OR = exp(estimate),
         lower_bound = exp(estimate - (1.96 * std_error)),
         upper_bound = exp(estimate + (1.96 * std_error)))

city_lr %>% 
  filter(term == 'victim_racenon-white') %>% 
  select(city, OR, lower_bound, upper_bound) %>% 
  knitr::kable()
```

Plot of estimated ORs and CIs for all cities
```{r}
city_lr %>% 
  mutate(city = as.factor(city),
         city = fct_reorder(city, OR)) %>% 
  filter(term == 'victim_racenon-white') %>%
  ggplot(aes(x = city, y = OR)) +
  geom_point() +
  geom_errorbar(aes(ymin = lower_bound, ymax = upper_bound)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title = 'OR (and 95% CI) for each City'
  )

```

Commenttttttttt

# Problem 2
